{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "helloworl.serviceAccountName" . }}
  labels:
{{ include "helloworl.labels" . | nindent 4 }}
{{- end -}}
